#!/usr/bin/env python3
"""
Foundry — Hybrid ML Pricing Model Retrainer
============================================
Blends three data tiers in priority order:

  Tier 1 (highest quality)  data/foundry_exports/{equipment}.csv
      Real accepted quotes from Foundry customers. Logged by the app
      whenever a quote is accepted. Export via: python scripts/export_foundry_data.py

  Tier 2 (good quality)     data/real_pricing/{equipment}.csv
      Scraped / rate-table data from Indian market sources.
      Generated by: python scripts/collect_pricing_data.py

  Tier 3 (fallback)         synthetic generation (same logic as original train_models.py)
      Used only when Tier 1 + Tier 2 combined are below the minimum threshold.

Blending rules (per equipment type):
  combined < 150 rows  →  70 % synthetic + 30 % real
  150 ≤ combined < 400 →  50 % synthetic + 50 % real
  ≥ 400 rows           →  real data only

Run:  python scripts/retrain_models.py
"""

import csv
import json
import logging
import os
from pathlib import Path

import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_percentage_error, r2_score
from sklearn.model_selection import train_test_split

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger(__name__)

np.random.seed(42)

BASE          = Path(__file__).parent.parent
REAL_DIR      = BASE / "data" / "real_pricing"
FOUNDRY_DIR   = BASE / "data" / "foundry_exports"
MODEL_DIR     = BASE / "src" / "lib" / "models"
MODEL_DIR.mkdir(parents=True, exist_ok=True)

BLEND_ONLY_REAL   = 400   # use purely real data above this
BLEND_HALF        = 150   # 50/50 blend above this
# below BLEND_HALF  → 30 % real + 70 % synthetic


# ─── GBM helpers (identical to train_models.py) ────────────────────────────

def serialize_tree(tree_obj):
    cl, cr, feat, thr, val = (
        tree_obj.children_left, tree_obj.children_right,
        tree_obj.feature, tree_obj.threshold, tree_obj.value,
    )
    def build(nid):
        if cl[nid] == -1:
            return {"v": round(float(val[nid, 0, 0]), 6)}
        return {"f": int(feat[nid]), "t": round(float(thr[nid]), 6),
                "l": build(cl[nid]), "r": build(cr[nid])}
    return build(0)


def train_and_export(name: str, X: np.ndarray, y: np.ndarray,
                     feature_names: list[str], n_real: int) -> None:
    X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.20, random_state=42)
    model = GradientBoostingRegressor(
        n_estimators=120, max_depth=4, learning_rate=0.07,
        min_samples_leaf=4, subsample=0.85, random_state=42,
    )
    model.fit(X_tr, y_tr)

    y_pred = model.predict(X_te)
    mape   = mean_absolute_percentage_error(np.exp(y_te), np.exp(y_pred))
    r2     = r2_score(y_te, y_pred)

    trees   = [serialize_tree(est[0].tree_) for est in model.estimators_]
    payload = {
        "equipment": name,
        "features": feature_names,
        "init_value": round(float(model.init_.constant_[0, 0]), 6),
        "learning_rate": model.learning_rate,
        "trees": trees,
    }
    path = MODEL_DIR / f"{name}.json"
    with open(path, "w") as fh:
        json.dump(payload, fh, separators=(",", ":"))

    kb = os.path.getsize(path) / 1024
    log.info("  [%s]  MAPE=%.1f%%  R²=%.3f  rows=%d  real=%d  size=%.0fKB",
             name, mape * 100, r2, len(X), n_real, kb)


# ─── CSV loaders ────────────────────────────────────────────────────────────

def load_csv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def float_row(row: dict, keys: list[str]) -> list[float] | None:
    try:
        return [float(row[k]) for k in keys]
    except (KeyError, ValueError):
        return None


# ─── Synthetic fallbacks (calibrated, same as collect_pricing_data.py) ─────

def synth_3d_printer(n: int) -> tuple[np.ndarray, np.ndarray]:
    rows, prices = [], []
    for _ in range(n):
        vol   = float(np.clip(np.random.lognormal(2.6, 1.3), 2.0, 500.0))
        inf   = np.random.choice([0.15, 0.20, 0.30, 0.50, 0.80])
        lay   = np.random.choice([0.10, 0.20, 0.30])
        mat   = int(np.random.choice([0, 1, 2, 3], p=[0.50, 0.18, 0.24, 0.08]))
        tri   = float(np.clip(np.random.lognormal(9.5, 1.6), 500.0, 700_000.0))
        qty   = int(np.random.choice([1, 2, 3, 5, 10]))
        RATE  = [6.0, 7.5, 8.5, 20.0][mat]
        DENS  = [1.24, 1.05, 1.27, 1.15][mat]
        wt    = vol * inf * DENS
        hrs   = max(0.25, (vol * inf) / (8.0 * (lay / 0.2) * (0.35 if mat == 3 else 1.0)))
        sup   = 1.25 if (mat == 3 or tri > 120_000) else 1.0
        cmplx = 1.0 + 0.10 * min(2.0, max(0.0, np.log10(tri / 20_000 + 0.1)))
        total = (wt * RATE + hrs * 80.0) * cmplx * sup * qty * (0.90 if qty >= 5 else 1.0)
        price = max(300.0, total * 1.12 * np.random.uniform(0.82, 1.18))
        rows.append([np.log(vol + 1), inf, lay, float(mat), np.log(tri + 1) / 13.5, float(qty)])
        prices.append(np.log(price))
    return np.array(rows), np.array(prices)


def synth_pcb(n: int) -> tuple[np.ndarray, np.ndarray]:
    rows, prices = [], []
    for _ in range(n):
        w    = float(np.random.uniform(20, 250))
        h    = float(np.random.uniform(20, 200))
        area = (w * h) / 100.0
        lay  = float(np.random.choice([1, 2, 4, 6, 8]))
        qty  = int(np.random.choice([5, 10, 20, 50, 100, 500]))
        trc  = float(np.random.choice([0.1, 0.127, 0.15, 0.2, 0.3]))
        suf  = float(np.random.choice([0, 1, 2]))
        mult = {1: 0.8, 2: 1.0, 4: 2.2, 6: 3.8, 8: 5.5}[int(lay)]
        usd  = max(2.0, area * 0.008 * mult * qty * max(0.45, 1.0 - 0.004 * (qty - 5))
                   * (1.0 + max(0, (0.15 - trc) * 15)) + [0.0, 13.2, 3.5][int(suf)])
        price = max(200.0, usd * 83.5 * 1.30 * np.random.uniform(0.88, 1.12))
        rows.append([np.log(area + 1), lay, float(qty), trc, suf])
        prices.append(np.log(price))
    return np.array(rows), np.array(prices)


def synth_cnc(n: int) -> tuple[np.ndarray, np.ndarray]:
    rows, prices = [], []
    HR = [(280, 480), (250, 450), (450, 750), (650, 1100)]
    for _ in range(n):
        vol   = float(np.clip(np.random.lognormal(3.5, 1.5), 5.0, 5000.0))
        mat   = int(np.random.choice([0, 1, 2, 3], p=[0.30, 0.25, 0.32, 0.13]))
        cmplx = float(np.random.randint(1, 6))
        setup = float(np.random.choice([1, 2, 3]))
        hr    = np.random.uniform(*HR[mat])
        hrs   = max(0.5, min((vol / 80.0) * (cmplx / 2.5) * [1.0, 0.9, 1.6, 2.2][mat], 20.0))
        price = max(400.0, (hrs * hr + setup * np.random.uniform(200, 600)) * np.random.uniform(0.88, 1.22))
        rows.append([np.log(vol + 1), float(mat), cmplx, setup])
        prices.append(np.log(price))
    return np.array(rows), np.array(prices)


def synth_lathe(n: int) -> tuple[np.ndarray, np.ndarray]:
    rows, prices = [], []
    HR = [(280, 520), (220, 400), (260, 430), (180, 320)]
    for _ in range(n):
        dia  = float(np.random.uniform(10, 300))
        leng = float(np.random.uniform(20, 600))
        mat  = int(np.random.choice([0, 1, 2, 3], p=[0.38, 0.30, 0.18, 0.14]))
        prec = int(np.random.choice([0, 1], p=[0.65, 0.35]))
        ops  = int(np.random.randint(1, 6))
        hr   = np.random.uniform(*HR[mat])
        hrs  = max(0.25, min((dia / 50.0) * (leng / 100.0) * (ops / 2.0) * (1.4 if prec else 1.0), 12.0))
        price = max(200.0, hrs * hr * np.random.uniform(0.84, 1.24))
        rows.append([np.log(dia + 1), np.log(leng + 1), float(mat), float(prec), float(ops)])
        prices.append(np.log(price))
    return np.array(rows), np.array(prices)


def synth_laser(n: int) -> tuple[np.ndarray, np.ndarray]:
    rows, prices = [], []
    for _ in range(n):
        w    = float(np.random.uniform(50, 900))
        h    = float(np.random.uniform(50, 600))
        mat  = int(np.random.choice([0, 1, 2, 3, 4, 5], p=[0.30, 0.28, 0.18, 0.08, 0.10, 0.06]))
        thk  = float(np.random.choice([2, 3, 4, 5, 6, 8, 10, 12]))
        qty  = int(np.random.choice([1, 2, 5, 10, 20]))
        cuts = float(np.random.randint(1, 15))
        area = (w * h) / 100.0
        peri = (2 * (w + h) + cuts * np.random.uniform(50, 300)) / 10.0
        AR   = [2.3, 3.9, 2.1, 3.1, 1.1, 1.8][mat]
        CR   = [0.9, 1.4, 0.8, 1.1, 0.5, 0.8][mat]
        pen  = 1.0 + 0.08 * max(0, thk - 3)
        price = max(150.0, (area * AR + peri * CR) * pen * 100 * qty
                   * (0.88 if qty >= 10 else 1.0) * np.random.uniform(0.82, 1.20))
        rows.append([np.log(area + 1), np.log(peri + 1), float(mat), thk, float(qty)])
        prices.append(np.log(price))
    return np.array(rows), np.array(prices)


def synth_waterjet(n: int) -> tuple[np.ndarray, np.ndarray]:
    rows, prices = [], []
    HR = [(900, 1600), (1100, 2000), (750, 1300), (1000, 1800), (1200, 2200)]
    SPD = [400, 180, 350, 80, 60]
    for _ in range(n):
        cl   = float(np.random.uniform(100, 8000))
        area = float(np.random.uniform(20, 2000))
        mat  = int(np.random.choice([0, 1, 2, 3, 4], p=[0.30, 0.22, 0.25, 0.14, 0.09]))
        thk  = float(np.random.choice([3, 5, 6, 8, 10, 12, 15, 20, 25]))
        qty  = int(np.random.choice([1, 2, 3, 5]))
        spd  = max(20.0, SPD[mat] / (1.0 + 0.10 * (thk - 5)))
        hr   = np.random.uniform(*HR[mat])
        price = max(500.0, ((cl / spd / 60.0) * hr * (1 + 0.06 * max(0, thk - 6)) + 400)
                   * qty * (0.92 if qty >= 3 else 1.0) * np.random.uniform(0.84, 1.22))
        rows.append([np.log(cl + 1), np.log(area + 1), float(mat), thk, float(qty)])
        prices.append(np.log(price))
    return np.array(rows), np.array(prices)


def synth_soldering(n: int) -> tuple[np.ndarray, np.ndarray]:
    rows, prices = [], []
    for _ in range(n):
        tht  = float(np.random.randint(0, 80))
        smd  = float(np.random.randint(0, 200))
        area = float(np.random.uniform(4, 400))
        dbl  = float(np.random.choice([0, 1]))
        bga  = float(np.random.choice([0, 0, 0, 1, 2, 3]))
        qty  = int(np.random.choice([1, 2, 5, 10, 25]))
        cost = (tht * np.random.uniform(12, 22) + smd * np.random.uniform(5, 10)
                + bga * np.random.uniform(220, 420))
        price = max(200.0, (cost + np.random.uniform(200, 350) + area * 0.6)
                   * (np.random.uniform(1.4, 1.6) if dbl else 1.0)
                   * qty * (0.82 if qty >= 10 else 1.0) * np.random.uniform(0.84, 1.22))
        rows.append([tht, smd, np.log(area + 1), dbl, bga, float(qty)])
        prices.append(np.log(price))
    return np.array(rows), np.array(prices)


def synth_vinyl(n: int) -> tuple[np.ndarray, np.ndarray]:
    rows, prices = [], []
    RATE = [(1.8, 3.2), (2.4, 4.2), (3.2, 5.5), (2.8, 4.8)]
    for _ in range(n):
        w    = float(np.random.uniform(50, 1200))
        h    = float(np.random.uniform(50, 800))
        mat  = int(np.random.choice([0, 1, 2, 3], p=[0.45, 0.30, 0.15, 0.10]))
        col  = float(np.random.randint(1, 6))
        qty  = int(np.random.choice([1, 2, 5, 10, 25, 50]))
        area = (w * h) / 100.0
        r    = np.random.uniform(*RATE[mat])
        price = max(80.0, (area * r + (col - 1) * np.random.uniform(50, 80) + 110)
                   * qty * (0.80 if qty >= 25 else (0.88 if qty >= 10 else 1.0))
                   * np.random.uniform(0.84, 1.20))
        rows.append([np.log(area + 1), float(mat), col, float(qty)])
        prices.append(np.log(price))
    return np.array(rows), np.array(prices)


# ─── Feature extractors: CSV row → (feature_vector, log_price) ─────────────
# Keys MUST match the column names written by collect_pricing_data.py
# and export_foundry_data.py.

EQUIPMENT_CONFIG: dict[str, dict] = {
    "3d-printer": {
        "csv_feats": ["volume_cm3", "infill", "layer_height_mm", "material_code",
                      "triangle_count", "quantity"],
        "model_feats": ["log_volume_cm3", "infill", "layer_height_mm",
                        "material_code", "log_complexity_norm", "quantity"],
        "transform": lambda r: [
            np.log(float(r["volume_cm3"]) + 1),
            float(r["infill"]),
            float(r["layer_height_mm"]),
            float(r["material_code"]),
            np.log(float(r["triangle_count"]) + 1) / 13.5,
            float(r["quantity"]),
        ],
        "synth_fn": synth_3d_printer,
    },
    "pcb-fabrication": {
        "csv_feats": ["area_cm2", "layers", "quantity", "min_trace_mm", "surface_finish_code"],
        "model_feats": ["log_area_cm2", "layers", "quantity", "min_trace_mm", "surface_finish_code"],
        "transform": lambda r: [
            np.log(float(r["area_cm2"]) + 1),
            float(r["layers"]),
            float(r["quantity"]),
            float(r["min_trace_mm"]),
            float(r["surface_finish_code"]),
        ],
        "synth_fn": synth_pcb,
    },
    "cnc-mill": {
        "csv_feats": ["stock_volume_cm3", "material_code", "complexity_1_5", "num_setups"],
        "model_feats": ["log_stock_vol_cm3", "material_code", "complexity_1_5", "num_setups"],
        "transform": lambda r: [
            np.log(float(r["stock_volume_cm3"]) + 1),
            float(r["material_code"]),
            float(r["complexity_1_5"]),
            float(r["num_setups"]),
        ],
        "synth_fn": synth_cnc,
    },
    "lathe": {
        "csv_feats": ["diameter_mm", "length_mm", "material_code", "is_precision", "num_operations"],
        "model_feats": ["log_diameter_mm", "log_length_mm", "material_code",
                        "is_precision", "num_operations"],
        "transform": lambda r: [
            np.log(float(r["diameter_mm"]) + 1),
            np.log(float(r["length_mm"]) + 1),
            float(r["material_code"]),
            float(r["is_precision"]),
            float(r["num_operations"]),
        ],
        "synth_fn": synth_lathe,
    },
    "laser-cutter": {
        "csv_feats": ["width_mm", "height_mm", "material_code", "thickness_mm",
                      "quantity", "num_cut_paths"],
        "model_feats": ["log_area_cm2", "log_perimeter_cm", "material_code",
                        "thickness_mm", "quantity"],
        "transform": lambda r: [
            np.log((float(r["width_mm"]) * float(r["height_mm"])) / 100.0 + 1),
            np.log((2 * (float(r["width_mm"]) + float(r["height_mm"]))
                    + float(r["num_cut_paths"]) * 150) / 10.0 + 1),
            float(r["material_code"]),
            float(r["thickness_mm"]),
            float(r["quantity"]),
        ],
        "synth_fn": synth_laser,
    },
    "water-jet": {
        "csv_feats": ["cut_length_mm", "area_cm2", "material_code", "thickness_mm", "quantity"],
        "model_feats": ["log_cut_length_mm", "log_area_cm2", "material_code",
                        "thickness_mm", "quantity"],
        "transform": lambda r: [
            np.log(float(r["cut_length_mm"]) + 1),
            np.log(float(r["area_cm2"]) + 1),
            float(r["material_code"]),
            float(r["thickness_mm"]),
            float(r["quantity"]),
        ],
        "synth_fn": synth_waterjet,
    },
    "soldering": {
        "csv_feats": ["tht_count", "smd_count", "board_area_cm2", "is_double_sided",
                      "bga_count", "qty_boards"],
        "model_feats": ["tht_count", "smd_count", "log_board_area_cm2",
                        "is_double_sided", "bga_count", "qty_boards"],
        "transform": lambda r: [
            float(r["tht_count"]),
            float(r["smd_count"]),
            np.log(float(r["board_area_cm2"]) + 1),
            float(r["is_double_sided"]),
            float(r["bga_count"]),
            float(r["qty_boards"]),
        ],
        "synth_fn": synth_soldering,
    },
    "vinyl-cutter": {
        "csv_feats": ["width_mm", "height_mm", "material_code", "color_count", "quantity"],
        "model_feats": ["log_area_cm2", "material_code", "color_count", "quantity"],
        "transform": lambda r: [
            np.log((float(r["width_mm"]) * float(r["height_mm"])) / 100.0 + 1),
            float(r["material_code"]),
            float(r["color_count"]),
            float(r["quantity"]),
        ],
        "synth_fn": synth_vinyl,
    },
}


def load_real_data(name: str, cfg: dict) -> tuple[np.ndarray, np.ndarray, int]:
    """Load Tier 1 (Foundry) + Tier 2 (scraped) data and apply feature transform."""
    rows_X, rows_y = [], []

    for src_dir in [FOUNDRY_DIR, REAL_DIR]:
        for row in load_csv(src_dir / f"{name}.csv"):
            try:
                x = cfg["transform"](row)
                y = np.log(float(row["price_inr"]))
                rows_X.append(x)
                rows_y.append(y)
            except Exception:
                pass

    if not rows_X:
        return np.empty((0, 0)), np.empty(0), 0
    return np.array(rows_X), np.array(rows_y), len(rows_X)


def blend(name: str, cfg: dict) -> tuple[np.ndarray, np.ndarray, int]:
    X_real, y_real, n_real = load_real_data(name, cfg)

    if n_real >= BLEND_ONLY_REAL:
        log.info("  %s: %d real rows — using real data only", name, n_real)
        return X_real, y_real, n_real

    # How many synthetic rows to add
    if n_real >= BLEND_HALF:
        n_synth = n_real            # 50/50
        log.info("  %s: %d real rows — blending 50/50 with synthetic", name, n_real)
    else:
        n_synth = max(300, n_real * 7 // 3)  # ~70% synthetic
        log.info("  %s: %d real rows — blending 30/70 real/synthetic", name, n_real)

    X_s, y_s = cfg["synth_fn"](n_synth)

    if n_real == 0:
        return X_s, y_s, 0

    X = np.vstack([X_real, X_s])
    y = np.concatenate([y_real, y_s])
    return X, y, n_real


# ─── MAIN ────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    log.info("Foundry — Hybrid ML Pricing Model Retrainer")
    log.info("=" * 52)

    for name, cfg in EQUIPMENT_CONFIG.items():
        X, y, n_real = blend(name, cfg)
        train_and_export(name, X, y, cfg["model_feats"], n_real)

    log.info("")
    log.info("Done. Model files written to %s", MODEL_DIR)
    log.info("Restart the Next.js dev server to pick up the new models.")
